# Chlorambucil cytotoxicity to leukemia cells

Equation (1) by Valle et al. in 'Chemoimmunotherapy administration protocol design for the treatment of leukemia through mathematical modelling and in silico experimentation':

$\mu _{AC}\left( \varkappa \right) =\left[ \log _{10}\left( 1+\varepsilon_{1}\varkappa \right) \right] ^{1/\varepsilon _{2}}$

where

$\varkappa:$ Chlorambucil concentration in mg/L.

In [8]:
import numpy
from scipy.optimize import curve_fit
import math

"""Observed data
Time and data needs to be concatenated in a 1D array for function curve_fit(Equations, tdata, odata,...) :
tdata and odata need to be the same length. Hence, for each variable in odata 
the time data needs to be repeated in odata, as follows:

tdata = |to|    odata = |xo|
"""
xo=numpy.array([0,1.5625,3.125,6.25,12.5,25,50])*(1E-6)*(304.212)*(1E3);
print('Chlorambucil concentration in mg/L:')
print(xo)
yo=numpy.array([0,0.003,0.004,0.006,0.0088,0.0126,0.018])*24;
print('Experimental chlorambucil cytotoxicity rates:')
print(yo)

"""Function where the mathematical model is defined and returns the fitted solutions:"""
def Equations(x,P1,P2):
    return (numpy.log10(1+P1*x))**(1/P2)

"""Fitting the observed data to the solutions of the mathematical model defined in Equations"""
npar=2 #Number of parameters to be fitted in the mathematical model defined in Equations
low=numpy.zeros(npar) #Lower bound for the parameters values to be fitted
sup=numpy.ones(npar)*math.inf #Superior bound for the parameters values to be fitted
p0=[1E-2,1] #Initial guess for the parameters values
popt, pcov = curve_fit(Equations, xo, yo, p0, bounds=(low,sup)); #curve_fit function
print('Fitted parameter values for Equation (1):')
print(popt) #Fitted parameters values

"""Solving the mathematical model defined in Equations with the fitted parameters"""
ya=Equations(xo,*popt) #Apprtoximated values
print('Fitted chlorambucil cytotoxicity rates:')
print(ya)

Chlorambucil concentration in mg/L:
[ 0.          0.47533125  0.9506625   1.901325    3.80265     7.6053
 15.2106    ]
Experimental chlorambucil cytotoxicity rates:
[0.     0.072  0.096  0.144  0.2112 0.3024 0.432 ]
Fitted parameter values for Equation (1):
[0.04799253 1.69300278]
Fitted chlorambucil cytotoxicity rates:
[0.         0.06506971 0.09735138 0.14474792 0.2127657  0.30659691
 0.42836431]


# CAR-T cells cytotoxicity to leukemia cells

Equation (5) by Valle et al. in 'Chemoimmunotherapy administration protocol design for the treatment of leukemia through mathematical modelling and in silico experimentation':

$\alpha _{T}\left( \rho _{T},\mu _{T},\rho _{A}\right) =\gamma _{1}+\dfrac{%
\mu _{T}\rho _{T}}{\gamma _{2}+\mu _{T}\rho _{T}}+\dfrac{\rho _{A}\rho _{T}}{%
\gamma _{3}+\rho _{A}\rho _{T}}$

where

$\rho _{T}:$ CAR-T cells mitosis stimulation rate,

$\mu _{T}:$ CAR-T cells natural death rate,

$\rho _{A}:$ Leukemia cells growth rate.

In [10]:
import numpy
from scipy.optimize import curve_fit
import math

"""Observed data
Time and data needs to be concatenated in a 1D array for function curve_fit(Equations, tdata, odata,...) :
tdata and odata need to be the same length. Hence, for each variable in odata 
the time data needs to be repeated in odata, as follows:

tdata = |to|    odata = |xo|
"""

rhoT=numpy.array([2.786E-08,2.880E-8,3.170E-8,3.022E-8,3.120E-8,3.392E-8])
print('CAR-T cells mitosis stimulation rates:')
print(rhoT)
muT=numpy.array([1/30,1/14])
print('CAR-T cells natural death rates:')
print(muT)
rhoA=numpy.array([1/60,1/40,1/20])
print('Leukemia cells growth rates:')
print(rhoA)
xo=numpy.concatenate((rhoT,muT,rhoA))
alphaT=numpy.array([1.393E-7,1.440E-7,1.585E-7,1.511E-7,1.560E-7,1.696E-7])
print('Experimental CAR-T cells cytotoxicity rates:')
print(alphaT)

def cytotoxicity(xo,g1,g2,g3):
    y1 = g1 + numpy.divide(muT[0]*rhoT[0:3],g2+muT[0]*rhoT[0:3]) + numpy.divide(numpy.multiply(rhoA,rhoT[0:3]),g3+numpy.multiply(rhoA,rhoT[0:3]))
    y2 = g1 + numpy.divide(muT[1]*rhoT[3:6],g2+muT[0]*rhoT[3:6]) + numpy.divide(numpy.multiply(rhoA,rhoT[3:6]),g3+numpy.multiply(rhoA,rhoT[3:6]))
    return numpy.concatenate((y1,y2))/1E-7

"""Fitting the observed data to the solutions of the mathematical model defined in Equations"""
Ig=[1E-7,1E-1,1E-1] #Initial guess for the parameters values
low=numpy.zeros(len(Ig)) #Lower bound for the parameters values to be fitted
sup=numpy.ones(len(Ig))*math.inf #Superior bound for the parameters values to be fitted
popt, pcov = curve_fit(cytotoxicity, xo, alphaT/(1E-7), Ig, bounds=(low,sup)); #curve_fit function
print('Fitted parameters values for Equation (5):')
print(popt) #Fitted parameters values

"""Solving the mathematical model defined in Equations with the fitted parameters"""
alphaT_fit=cytotoxicity(xo,*popt)*1E-7 #Apprtoximated values
print('Fitted CAR-T cells cytotoxicity rates:')
print(alphaT_fit)

CAR-T cells mitosis stimulation rates:
[2.786e-08 2.880e-08 3.170e-08 3.022e-08 3.120e-08 3.392e-08]
CAR-T cells natural death rates:
[0.03333333 0.07142857]
Leukemia cells growth rates:
[0.01666667 0.025      0.05      ]
Experimental CAR-T cells cytotoxicity rates:
[1.393e-07 1.440e-07 1.585e-07 1.511e-07 1.560e-07 1.696e-07]
Fitted parameters values for Equation (5):
[1.25630251e-07 1.22119816e-01 6.77666812e-02]
Fitted CAR-T cells cytotoxicity rates:
[1.40086746e-07 1.44116073e-07 1.57672030e-07 1.50738464e-07
 1.55389388e-07 1.70497298e-07]
